### ISSUE TITLE
Run grid search on a custom environment

### ISSUE THREAD

**Issue by bchasnov** [singerGUO/gym_multiagent_control#1]
Run a grid search of RL algorithms and parameters with an OpenAI's `ExperimentGrid` test bench and a custom gym environment.
Let it run overnight, then plot and summarize the results.

**Comment by bchasnov** [comment]
To plot results, run
```
cd spinningup
python3 -m spinup.run plot EXP_DIR
```
where `EXP_DIR` is where the data is stored, for e.g. `data/ppo-pyt-bench_gym_multiagent_control-foo-v0_hid64-64_relu/ppo-pyt-bench_gym_multiagent_control-foo-v0_hid64-64_relu_s20`

**Comment by singerGUO** [comment]
Deactivate the virtual Environment for Training doesn't work with Virtual Environment could not run within virtual environment  because it could not find gym_multiagent_control module

Open the 2020-06-23-143220.x11

1. Test training with local environment **LunarLander-v2**

`python -m spinup.run ppo --hid "[32,32]" --env LunarLander-v2 --exp_name installtest --gamma 0.999
`

2. Check the spinningup plotting and visualization is working 

`python3 -m spinup.run test_policy data/installtest/installtest_s0`

![image](https://user-images.githubusercontent.com/35857115/87484444-016b0a00-c5eb-11ea-9c15-eae022b9a29a.png)

3. Visualize the train policy

`python3 -m spinup.run test_policy /projects/ac66b0d1-d01e-42cc-9d9b-3799ed5ac4d1/spinningup/data/installtest/installtest_s0`

![image](https://user-images.githubusercontent.com/35857115/87485243-2fe9e480-c5ed-11ea-9873-a5cfa020ae59.png)

Then Test the Grid Experiments is working with 

`cd gym_multiagent_control/gym_multiagent_control/envs`
`python3 bench.py`

and plot the result with 
`python3 -m spinup.run plot /projects/ac66b0d1-d01e-42cc-9d9b-3799ed5ac4d1/spinningup/data/ppo-pyt-bench_gym_multiagent_control-foo-v0_hid64-64_relu/ppo-pyt-bench_gym_multiagent_control-foo-v0_hid64-64_relu_s20
`

![image](https://user-images.githubusercontent.com/35857115/87486271-c15a5600-c5ef-11ea-9857-c2170eeeb3a8.png)

Training is not working properly in the our own enviroment (Need to be fixed)

**Comment by singerGUO** [comment]
Used CartPole as Enviroment instead of MountainCar in custom Enviroment and the results of experiment grid is shown in data folder
![image](https://user-images.githubusercontent.com/35857115/87517350-985bb480-c633-11ea-81dc-53a85093c34e.png)

Run `python3 -m spinup.run plot /projects/ac66b0d1-d01e-42cc-9d9b-3799ed5ac4d1/spinningup/data/ppo-test-cart_gym_multiagent_control-foo-v1_hid64-64_relu/ppo-test-cart_gym_multiagent_control-foo-v1_hid64-64_relu_s20` 
and it shows like the experiments performance properly
![image](https://user-images.githubusercontent.com/35857115/87517820-48c9b880-c634-11ea-94bf-943d411cae35.png)

**Comment by singerGUO** [comment]
Grid search also works in lunar
![image](https://user-images.githubusercontent.com/35857115/87520871-68fb7680-c638-11ea-9693-6d1d13d4c02d.png)
